version: '3'
services:
  web:
    build: ./docker/php
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=app.dev
    volumes:
      - .:/codes/php-junior
    depends_on:
      - db
  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  db:
